import { Injectable, Logger } from "@nestjs/common";
import { ReportType } from "../domain/reports";
import { PreparedReportData } from "./data-preparation.service";
import * as ExcelJS from "exceljs";

export interface ExcelGenerationOptions {
  reportType: ReportType;
  startDate: string;
  endDate: string;
  siteId?: string;
  provinceId?: string;
  generatedBy: string;
  reportName?: string;
  reportOptions?: any;
  contentMetadata?: any;
}

@Injectable()
export class ExcelGenerationService {
  private readonly logger = new Logger(ExcelGenerationService.name);

  async generateReportExcel(data: PreparedReportData): Promise<Buffer> {
    this.logger.log(`Generating Excel for report type: ${data.reportType}`);

    try {
      const workbook = new ExcelJS.Workbook();

      // Set workbook properties
      workbook.creator = data.reportInfo.generatedBy;
      workbook.created = new Date();
      workbook.modified = new Date();
      workbook.lastModifiedBy = data.reportInfo.generatedBy;

      // Generate worksheet based on report type
      switch (data.reportType) {
        case ReportType.CAMERA_PERFORMANCE:
          this.generateCameraPerformanceWorksheet(workbook, data);
          break;
        case ReportType.BREACH_SUMMARY:
          this.generateBreachSummaryWorksheet(workbook, data);
          break;
        case ReportType.TRANSPORT_ACTIVITY:
          this.generateTransportActivityWorksheet(workbook, data);
          break;
        case ReportType.VOLUME_TRACKING:
          this.generateVolumeTrackingWorksheet(workbook, data);
          break;
        default:
          throw new Error(`Unsupported report type: ${data.reportType}`);
      }

      // Generate Excel buffer
      const buffer = await workbook.xlsx.writeBuffer();
      this.logger.log(
        `Excel generated successfully for report type: ${data.reportType}`,
      );

      return Buffer.from(buffer);
    } catch (error) {
      this.logger.error("Error generating Excel:", error);
      throw error;
    }
  }

  private generateCameraPerformanceWorksheet(
    workbook: ExcelJS.Workbook,
    data: PreparedReportData,
  ) {
    const worksheet = workbook.addWorksheet("Camera Performance Report");

    // Set column widths - 5 columns now
    worksheet.columns = [
      { width: 20 }, // Camera Name
      { width: 25 }, // Location
      { width: 12 }, // Status
      { width: 12 }, // Uptime %
      { width: 18 }, // Detection Accuracy
    ];

    // Add title
    worksheet.mergeCells("A1:E1");
    const titleCell = worksheet.getCell("A1");
    titleCell.value = data.reportInfo.title;
    titleCell.font = { size: 16, bold: true, color: { argb: "FF2C5AA0" } };
    titleCell.alignment = { horizontal: "center" };
    titleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF0F4FF" },
    };

    // Add report info
    worksheet.mergeCells("A2:E2");
    const periodCell = worksheet.getCell("A2");
    periodCell.value = `Period: ${data.reportInfo.period}`;
    periodCell.font = { size: 12, bold: true };
    periodCell.alignment = { horizontal: "center" };

    worksheet.mergeCells("A3:E3");
    const generatedByCell = worksheet.getCell("A3");
    generatedByCell.value = `Generated by: ${data.reportInfo.generatedBy} | Site: ${data.reportInfo.siteName} | Province: ${data.reportInfo.provinceName}`;
    generatedByCell.font = { size: 10 };
    generatedByCell.alignment = { horizontal: "center" };

    // Add summary section
    worksheet.mergeCells("A5:E5");
    const summaryTitleCell = worksheet.getCell("A5");
    summaryTitleCell.value = "Summary";
    summaryTitleCell.font = {
      size: 14,
      bold: true,
      color: { argb: "FF2C5AA0" },
    };
    summaryTitleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF0F4FF" },
    };

    // Summary data
    const summaryData = [
      ["Total Cameras", data.summary.totalCameras],
      ["Active Cameras", data.summary.activeCameras],
      ["Average Uptime", `${data.summary.averageUptime || 0}%`],
      ["Average Detection Accuracy", `${data.summary.averageAccuracy || 0}%`],
    ];

    summaryData.forEach((row, index) => {
      const rowNum = 6 + index;
      worksheet.getCell(`A${rowNum}`).value = row[0];
      worksheet.getCell(`B${rowNum}`).value = row[1];
      worksheet.getCell(`A${rowNum}`).font = { bold: true };
    });

    // Add headers - 5 columns now
    const headerRow = 11;
    const headers = [
      "Camera Name",
      "Location",
      "Status",
      "Uptime %",
      "Detection Accuracy",
    ];

    headers.forEach((header, index) => {
      const cell = worksheet.getCell(headerRow, index + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF2C5AA0" },
      };
      cell.alignment = { horizontal: "center" };
    });

    // Add data rows - 5 columns now
    data.data.performanceMetrics.forEach((metric, index) => {
      const rowNum = headerRow + 1 + index;
      const row = [
        metric.cameraName,
        metric.location,
        metric.status,
        `${metric.uptime}%`,
        `${metric.detectionAccuracy}%`,
      ];

      row.forEach((value, colIndex) => {
        const cell = worksheet.getCell(rowNum, colIndex + 1);
        cell.value = value;

        // Color code status
        if (colIndex === 2) {
          // Status column
          if (metric.status.toLowerCase() === "online") {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFD1E7DD" },
            };
            cell.font = { bold: true, color: { argb: "FF198754" } };
          } else {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8D7DA" },
            };
            cell.font = { bold: true, color: { argb: "FFDC3545" } };
          }
        }

        // Color code detection accuracy
        if (colIndex === 4) {
          // Detection Accuracy column
          const accuracy = metric.detectionAccuracy;
          if (accuracy >= 90) {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFD1E7DD" },
            };
            cell.font = { bold: true, color: { argb: "FF198754" } };
          } else if (accuracy >= 70) {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFFFF3CD" },
            };
            cell.font = { bold: true, color: { argb: "FFFD7E14" } };
          } else {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8D7DA" },
            };
            cell.font = { bold: true, color: { argb: "FFDC3545" } };
          }
        }
      });

      // Alternate row colors
      if (index % 2 === 0) {
        for (let col = 1; col <= headers.length; col++) {
          if (col !== 3 && col !== 5) {
            // Don't override status and accuracy colors
            worksheet.getCell(rowNum, col).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8F9FA" },
            };
          }
        }
      }
    });

    // Add footer
    const footerRow = headerRow + data.data.performanceMetrics.length + 2;
    worksheet.mergeCells(`A${footerRow}:E${footerRow}`);
    const footerCell = worksheet.getCell(`A${footerRow}`);
    footerCell.value = `Generated on ${data.reportInfo.generatedAt}`;
    footerCell.font = { size: 10, italic: true };
    footerCell.alignment = { horizontal: "center" };
  }

  private generateBreachSummaryWorksheet(
    workbook: ExcelJS.Workbook,
    data: PreparedReportData,
  ) {
    const worksheet = workbook.addWorksheet("Breach Summary Report");

    // Set column widths
    worksheet.columns = [
      { width: 12 }, // Date
      { width: 10 }, // Time
      { width: 20 }, // Location
      { width: 15 }, // Province
      { width: 20 }, // Type
      { width: 12 }, // Severity
      { width: 15 }, // Status
      { width: 30 }, // Description
    ];

    // Add title
    worksheet.mergeCells("A1:H1");
    const titleCell = worksheet.getCell("A1");
    titleCell.value = data.reportInfo.title;
    titleCell.font = { size: 16, bold: true, color: { argb: "FFFFFFFF" } };
    titleCell.alignment = { horizontal: "center" };
    titleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFDC3545" },
    };

    // Add report info
    worksheet.mergeCells("A2:H2");
    const periodCell = worksheet.getCell("A2");
    periodCell.value = `Period: ${data.reportInfo.period}`;
    periodCell.font = { size: 12, bold: true };
    periodCell.alignment = { horizontal: "center" };

    worksheet.mergeCells("A3:H3");
    const generatedByCell = worksheet.getCell("A3");
    generatedByCell.value = `Generated by: ${data.reportInfo.generatedBy} | Site: ${data.reportInfo.siteName} | Province: ${data.reportInfo.provinceName}`;
    generatedByCell.font = { size: 10 };
    generatedByCell.alignment = { horizontal: "center" };

    // Add summary section
    worksheet.mergeCells("A5:H5");
    const summaryTitleCell = worksheet.getCell("A5");
    summaryTitleCell.value = "Summary";
    summaryTitleCell.font = {
      size: 14,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    summaryTitleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFDC3545" },
    };

    // Summary data
    const summaryData = [
      ["Total Breaches", data.summary.totalBreaches],
      ["High Severity", data.summary.highSeverity],
      ["Medium Severity", data.summary.mediumSeverity],
      ["Low Severity", data.summary.lowSeverity],
      ["Resolved", data.summary.resolved],
      ["Open", data.summary.open],
    ];

    summaryData.forEach((row, index) => {
      const rowNum = 6 + index;
      worksheet.getCell(`A${rowNum}`).value = row[0];
      worksheet.getCell(`B${rowNum}`).value = row[1];
      worksheet.getCell(`A${rowNum}`).font = { bold: true };
    });

    // Add headers
    const headerRow = 13;
    const headers = [
      "Date",
      "Time",
      "Location",
      "Province",
      "Type",
      "Severity",
      "Status",
      "Description",
    ];

    headers.forEach((header, index) => {
      const cell = worksheet.getCell(headerRow, index + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFDC3545" },
      };
      cell.alignment = { horizontal: "center" };
    });

    // Add data rows
    data.data.breachDetails.forEach((breach, index) => {
      const rowNum = headerRow + 1 + index;
      const row = [
        new Date(breach.date).toLocaleDateString(),
        breach.time,
        breach.location,
        breach.province,
        breach.type,
        breach.severity,
        breach.status,
        breach.description,
      ];

      row.forEach((value, colIndex) => {
        const cell = worksheet.getCell(rowNum, colIndex + 1);
        cell.value = value;

        // Color code severity
        if (colIndex === 5) {
          // Severity column
          switch (breach.severity.toLowerCase()) {
            case "high":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFF8D7DA" },
              };
              cell.font = { bold: true, color: { argb: "FFDC3545" } };
              break;
            case "medium":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFF3CD" },
              };
              cell.font = { bold: true, color: { argb: "FFFD7E14" } };
              break;
            case "low":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFD1E7DD" },
              };
              cell.font = { bold: true, color: { argb: "FF198754" } };
              break;
          }
        }
      });

      // Alternate row colors
      if (index % 2 === 0) {
        for (let col = 1; col <= headers.length; col++) {
          if (col !== 6) {
            // Don't override severity colors
            worksheet.getCell(rowNum, col).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8F9FA" },
            };
          }
        }
      }
    });

    // Add footer
    const footerRow = headerRow + data.data.breachDetails.length + 2;
    worksheet.mergeCells(`A${footerRow}:H${footerRow}`);
    const footerCell = worksheet.getCell(`A${footerRow}`);
    footerCell.value = `Generated on ${data.reportInfo.generatedAt}`;
    footerCell.font = { size: 10, italic: true };
    footerCell.alignment = { horizontal: "center" };
  }

  private generateTransportActivityWorksheet(
    workbook: ExcelJS.Workbook,
    data: PreparedReportData,
  ) {
    const worksheet = workbook.addWorksheet("Transport Activity Report");

    // Set column widths - 10 columns now
    worksheet.columns = [
      { width: 12 }, // Date
      { width: 15 }, // Truck ID
      { width: 20 }, // Driver
      { width: 15 }, // Load Weight
      { width: 12 }, // Direction
      { width: 12 }, // Overloaded
      { width: 20 }, // Site
      { width: 15 }, // Status
      { width: 15 }, // Entry Time
      { width: 15 }, // Exit Time
    ];

    // Add title
    worksheet.mergeCells("A1:J1");
    const titleCell = worksheet.getCell("A1");
    titleCell.value = data.reportInfo.title;
    titleCell.font = { size: 16, bold: true, color: { argb: "FFFFFFFF" } };
    titleCell.alignment = { horizontal: "center" };
    titleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF28A745" },
    };

    // Add report info
    worksheet.mergeCells("A2:J2");
    const periodCell = worksheet.getCell("A2");
    periodCell.value = `Period: ${data.reportInfo.period}`;
    periodCell.font = { size: 12, bold: true };
    periodCell.alignment = { horizontal: "center" };

    worksheet.mergeCells("A3:J3");
    const generatedByCell = worksheet.getCell("A3");
    generatedByCell.value = `Generated by: ${data.reportInfo.generatedBy} | Site: ${data.reportInfo.siteName} | Province: ${data.reportInfo.provinceName}`;
    generatedByCell.font = { size: 10 };
    generatedByCell.alignment = { horizontal: "center" };

    // Add summary section
    worksheet.mergeCells("A5:J5");
    const summaryTitleCell = worksheet.getCell("A5");
    summaryTitleCell.value = "Summary";
    summaryTitleCell.font = {
      size: 14,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    summaryTitleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF28A745" },
    };

    // Summary data
    const summaryData = [
      ["Total Activities", data.summary.totalActivities],
      ["Total Weight (tons)", data.summary.totalWeight.toFixed(1)],
      ["Completed Trips", data.summary.completedTrips],
      ["Active Trips", data.summary.activeTrips],
      ["Unique Trucks", data.summary.uniqueTrucks],
      ["Average Weight (tons)", data.summary.averageWeight.toFixed(1)],
      ["Overloaded Trips", data.summary.overloadedTrips],
      ["Inbound Trips", data.summary.inboundTrips],
      ["Outbound Trips", data.summary.outboundTrips],
    ];

    summaryData.forEach((row, index) => {
      const rowNum = 6 + index;
      worksheet.getCell(`A${rowNum}`).value = row[0];
      worksheet.getCell(`B${rowNum}`).value = row[1];
      worksheet.getCell(`A${rowNum}`).font = { bold: true };
    });

    // Add headers - 10 columns now
    const headerRow = 16;
    const headers = [
      "Date",
      "Truck ID",
      "Driver",
      "Load Weight (tons)",
      "Direction",
      "Overloaded",
      "Site",
      "Status",
      "Entry Time",
      "Exit Time",
    ];

    headers.forEach((header, index) => {
      const cell = worksheet.getCell(headerRow, index + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF28A745" },
      };
      cell.alignment = { horizontal: "center" };
    });

    // Add data rows - 10 columns now
    data.data.activityDetails.forEach((activity, index) => {
      const rowNum = headerRow + 1 + index;
      const row = [
        new Date(activity.date).toLocaleDateString(),
        activity.truckId,
        activity.driver,
        activity.loadWeight.toFixed(1),
        activity.direction.toUpperCase(),
        activity.overloaded ? "YES" : "NO",
        activity.site,
        activity.status,
        activity.entryTime
          ? new Date(activity.entryTime).toLocaleTimeString()
          : "N/A",
        activity.exitTime
          ? new Date(activity.exitTime).toLocaleTimeString()
          : "N/A",
      ];

      row.forEach((value, colIndex) => {
        const cell = worksheet.getCell(rowNum, colIndex + 1);
        cell.value = value;

        // Color code direction
        if (colIndex === 4) {
          // Direction column
          if (activity.direction.toLowerCase() === "in") {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFD1E7DD" },
            };
            cell.font = { bold: true, color: { argb: "FF198754" } };
          } else {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8D7DA" },
            };
            cell.font = { bold: true, color: { argb: "FFDC3545" } };
          }
        }

        // Color code overloaded
        if (colIndex === 5) {
          // Overloaded column
          if (activity.overloaded) {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8D7DA" },
            };
            cell.font = { bold: true, color: { argb: "FFDC3545" } };
          } else {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFD1E7DD" },
            };
            cell.font = { bold: true, color: { argb: "FF198754" } };
          }
        }

        // Color code status
        if (colIndex === 7) {
          // Status column
          switch (activity.status) {
            case "completed":
            case "acknowledged":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFD1E7DD" },
              };
              cell.font = { bold: true, color: { argb: "FF198754" } };
              break;
            case "new":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFE2E3E5" },
              };
              cell.font = { bold: true, color: { argb: "FF007BFF" } };
              break;
            case "under_review":
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFF3CD" },
              };
              cell.font = { bold: true, color: { argb: "FFFD7E14" } };
              break;
            default:
              cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFF8F9FA" },
              };
              cell.font = { bold: true, color: { argb: "FF6C757D" } };
          }
        }
      });

      // Alternate row colors
      if (index % 2 === 0) {
        for (let col = 1; col <= headers.length; col++) {
          if (col !== 5 && col !== 6 && col !== 8) {
            // Don't override direction, overloaded, and status colors
            worksheet.getCell(rowNum, col).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8F9FA" },
            };
          }
        }
      }
    });

    // Add footer
    const footerRow = headerRow + data.data.activityDetails.length + 2;
    worksheet.mergeCells(`A${footerRow}:J${footerRow}`);
    const footerCell = worksheet.getCell(`A${footerRow}`);
    footerCell.value = `Generated on ${data.reportInfo.generatedAt}`;
    footerCell.font = { size: 10, italic: true };
    footerCell.alignment = { horizontal: "center" };
  }

  private generateVolumeTrackingWorksheet(
    workbook: ExcelJS.Workbook,
    data: PreparedReportData,
  ) {
    const worksheet = workbook.addWorksheet("Volume Tracking Report");

    // Set column widths - 8 columns now
    worksheet.columns = [
      { width: 12 }, // Date
      { width: 20 }, // Site
      { width: 15 }, // Volume
      { width: 12 }, // Fill Level
      { width: 12 }, // Overloaded
      { width: 15 }, // Truck ID
      { width: 15 }, // Entry Time
      { width: 15 }, // Exit Time
    ];

    // Add title
    worksheet.mergeCells("A1:H1");
    const titleCell = worksheet.getCell("A1");
    titleCell.value = data.reportInfo.title;
    titleCell.font = { size: 16, bold: true, color: { argb: "FFFFFFFF" } };
    titleCell.alignment = { horizontal: "center" };
    titleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFFD7E14" },
    };

    // Add report info
    worksheet.mergeCells("A2:H2");
    const periodCell = worksheet.getCell("A2");
    periodCell.value = `Period: ${data.reportInfo.period}`;
    periodCell.font = { size: 12, bold: true };
    periodCell.alignment = { horizontal: "center" };

    worksheet.mergeCells("A3:H3");
    const generatedByCell = worksheet.getCell("A3");
    generatedByCell.value = `Generated by: ${data.reportInfo.generatedBy} | Site: ${data.reportInfo.siteName} | Province: ${data.reportInfo.provinceName}`;
    generatedByCell.font = { size: 10 };
    generatedByCell.alignment = { horizontal: "center" };

    // Add summary section
    worksheet.mergeCells("A5:H5");
    const summaryTitleCell = worksheet.getCell("A5");
    summaryTitleCell.value = "Summary";
    summaryTitleCell.font = {
      size: 14,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    summaryTitleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFFD7E14" },
    };

    // Summary data
    const summaryData = [
      ["Total Volume (tons)", data.summary.totalVolume.toFixed(1)],
      ["Total Trips", data.summary.totalTrips],
      ["Unique Sites", data.summary.uniqueSites],
      ["Average Volume/Trip", data.summary.averageVolumePerTrip.toFixed(1)],
      ["Average Fill Level (%)", data.summary.averageFillLevel.toFixed(1)],
      ["Overloaded Trips", data.summary.overloadedTrips],
    ];

    summaryData.forEach((row, index) => {
      const rowNum = 6 + index;
      worksheet.getCell(`A${rowNum}`).value = row[0];
      worksheet.getCell(`B${rowNum}`).value = row[1];
      worksheet.getCell(`A${rowNum}`).font = { bold: true };
    });

    // Add site summary
    if (data.summary.siteSummary && data.summary.siteSummary.length > 0) {
      worksheet.mergeCells("A12:H12");
      const siteSummaryTitleCell = worksheet.getCell("A12");
      siteSummaryTitleCell.value = "Site Summary";
      siteSummaryTitleCell.font = {
        size: 14,
        bold: true,
        color: { argb: "FFFFFFFF" },
      };
      siteSummaryTitleCell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFFD7E14" },
      };

      // Site summary headers - 7 columns now
      const siteSummaryHeaders = [
        "Site",
        "Province",
        "Total Volume (tons)",
        "Trips",
        "Average Volume/Trip",
        "Average Fill Level (%)",
        "Overloaded Trips",
      ];
      siteSummaryHeaders.forEach((header, index) => {
        const cell = worksheet.getCell(13, index + 1);
        cell.value = header;
        cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFFD7E14" },
        };
        cell.alignment = { horizontal: "center" };
      });

      // Site summary data - 7 columns now
      data.summary.siteSummary.forEach((site, index) => {
        const rowNum = 14 + index;
        const row = [
          site.site,
          site.province,
          site.totalVolume.toFixed(1),
          site.trips,
          site.averageVolume.toFixed(1),
          site.averageFillLevel.toFixed(1),
          site.overloadedTrips,
        ];

        row.forEach((value, colIndex) => {
          worksheet.getCell(rowNum, colIndex + 1).value = value;
        });

        // Alternate row colors
        if (index % 2 === 0) {
          for (let col = 1; col <= siteSummaryHeaders.length; col++) {
            worksheet.getCell(rowNum, col).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8F9FA" },
            };
          }
        }
      });
    }

    // Add headers for detailed data - 8 columns now
    const headerRow =
      data.summary.siteSummary && data.summary.siteSummary.length > 0
        ? 15 + data.summary.siteSummary.length
        : 13;
    const headers = [
      "Date",
      "Site",
      "Volume (tons)",
      "Fill Level (%)",
      "Overloaded",
      "Truck ID",
      "Entry Time",
      "Exit Time",
    ];

    headers.forEach((header, index) => {
      const cell = worksheet.getCell(headerRow, index + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFFD7E14" },
      };
      cell.alignment = { horizontal: "center" };
    });

    // Add data rows - 8 columns now
    data.data.volumeDetails.forEach((volume, index) => {
      const rowNum = headerRow + 1 + index;
      const row = [
        new Date(volume.date).toLocaleDateString(),
        volume.site,
        volume.volume.toFixed(1),
        volume.fillLevel.toFixed(1),
        volume.overloaded ? "YES" : "NO",
        volume.truckId,
        volume.entryTime
          ? new Date(volume.entryTime).toLocaleTimeString()
          : "N/A",
        volume.exitTime
          ? new Date(volume.exitTime).toLocaleTimeString()
          : "N/A",
      ];

      row.forEach((value, colIndex) => {
        const cell = worksheet.getCell(rowNum, colIndex + 1);
        cell.value = value;

        // Color code overloaded
        if (colIndex === 4) {
          // Overloaded column
          if (volume.overloaded) {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8D7DA" },
            };
            cell.font = { bold: true, color: { argb: "FFDC3545" } };
          } else {
            cell.fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFD1E7DD" },
            };
            cell.font = { bold: true, color: { argb: "FF198754" } };
          }
        }
      });

      // Alternate row colors
      if (index % 2 === 0) {
        for (let col = 1; col <= headers.length; col++) {
          if (col !== 5) {
            // Don't override overloaded colors
            worksheet.getCell(rowNum, col).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF8F9FA" },
            };
          }
        }
      }
    });

    // Add footer
    const footerRow = headerRow + data.data.volumeDetails.length + 2;
    worksheet.mergeCells(`A${footerRow}:H${footerRow}`);
    const footerCell = worksheet.getCell(`A${footerRow}`);
    footerCell.value = `Generated on ${data.reportInfo.generatedAt}`;
    footerCell.font = { size: 10, italic: true };
    footerCell.alignment = { horizontal: "center" };
  }
}
