import { Injectable } from "@nestjs/common";
import { ReportType } from "../domain/reports";
import { PreparedReportData } from "./data-preparation.service";

export interface TemplateService {
  generateHtml(data: PreparedReportData): string;
}

@Injectable()
export class CameraPerformanceTemplateService implements TemplateService {
  generateHtml(data: PreparedReportData): string {
    const { reportInfo, data: reportData, summary } = data;

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportInfo.title}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
          .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { text-align: center; border-bottom: 3px solid #2c5aa0; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { color: #2c5aa0; margin: 0; font-size: 28px; }
          .header h2 { color: #666; margin: 10px 0 0 0; font-weight: normal; font-size: 16px; }
          .section { margin-bottom: 30px; }
          .section h3 { color: #2c5aa0; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; font-size: 20px; }
          .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .info-item { padding: 15px; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #2c5aa0; }
          .info-label { font-weight: bold; color: #333; font-size: 14px; }
          .info-value { color: #666; font-size: 16px; margin-top: 5px; }
          .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .summary-item { padding: 20px; background: linear-gradient(135deg, #2c5aa0, #1e3d72); color: white; border-radius: 8px; text-align: center; }
          .summary-value { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
          .summary-label { font-size: 14px; opacity: 0.9; }
          .metrics-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; }
          .metrics-table th, .metrics-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          .metrics-table th { background-color: #2c5aa0; color: white; font-weight: bold; }
          .metrics-table tr:nth-child(even) { background-color: #f8f9fa; }
          .status-active { color: #28a745; font-weight: bold; }
          .status-maintenance { color: #ffc107; font-weight: bold; }
          .status-inactive { color: #dc3545; font-weight: bold; }
          .status-online { color: #28a745; font-weight: bold; }
          .status-offline { color: #dc3545; font-weight: bold; }
          .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>${reportInfo.title}</h1>
            <h2>Period: ${reportInfo.period}</h2>
          </div>
          
          <div class="section">
            <h3>Report Information</h3>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Report Type:</div>
                <div class="info-value">Camera Performance</div>
              </div>
              <div class="info-item">
                <div class="info-label">Generated By:</div>
                <div class="info-value">${reportInfo.generatedBy}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Site:</div>
                <div class="info-value">${reportInfo.siteName}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Province:</div>
                <div class="info-value">${reportInfo.provinceName}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Performance Summary</h3>
            <div class="summary-grid">
              <div class="summary-item">
                <div class="summary-value">${summary.totalCameras}</div>
                <div class="summary-label">Total Cameras</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.activeCameras}</div>
                <div class="summary-label">Active Cameras</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.averageUptime || 0}%</div>
                <div class="summary-label">Average Uptime</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.averageAccuracy || 0}%</div>
                <div class="summary-label">Average Detection Accuracy</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Camera Performance Metrics</h3>
            <table class="metrics-table">
              <thead>
                <tr>
                  <th>Camera Name</th>
                  <th>Location</th>
                  <th>Status</th>
                  <th>Uptime %</th>
                  <th>Detection Accuracy</th>
                </tr>
              </thead>
              <tbody>
                ${reportData.performanceMetrics
                  .map(
                    (metric) => `
                  <tr>
                    <td>${metric.cameraName}</td>
                    <td>${metric.location}</td>
                    <td><span class="status-${metric.status.toLowerCase()}">${metric.status.charAt(0).toUpperCase() + metric.status.slice(1)}</span></td>
                    <td>${metric.uptime}%</td>
                    <td>${metric.detectionAccuracy}%</td>
                  </tr>
                `,
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>Generated on ${reportInfo.generatedAt}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

@Injectable()
export class BreachSummaryTemplateService implements TemplateService {
  generateHtml(data: PreparedReportData): string {
    const { reportInfo, data: reportData, summary } = data;

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportInfo.title}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
          .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { text-align: center; border-bottom: 3px solid #2c5aa0; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { color: #2c5aa0; margin: 0; font-size: 28px; }
          .header h2 { color: #666; margin: 10px 0 0 0; font-weight: normal; font-size: 16px; }
          .section { margin-bottom: 30px; }
          .section h3 { color: #2c5aa0; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; font-size: 20px; }
          .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .info-item { padding: 15px; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #2c5aa0; }
          .info-label { font-weight: bold; color: #333; font-size: 14px; }
          .info-value { color: #666; font-size: 16px; margin-top: 5px; }
          .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .summary-item { padding: 20px; background: linear-gradient(135deg, #2c5aa0, #1e3d72); color: white; border-radius: 8px; text-align: center; }
          .summary-value { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
          .summary-label { font-size: 14px; opacity: 0.9; }
          .breach-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; }
          .breach-table th, .breach-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          .breach-table th { background-color: #2c5aa0; color: white; font-weight: bold; }
          .breach-table tr:nth-child(even) { background-color: #f8f9fa; }
          .severity-high { color: #dc3545; font-weight: bold; background-color: #f8d7da; padding: 4px 8px; border-radius: 4px; }
          .severity-medium { color: #fd7e14; font-weight: bold; background-color: #fff3cd; padding: 4px 8px; border-radius: 4px; }
          .severity-low { color: #198754; font-weight: bold; background-color: #d1e7dd; padding: 4px 8px; border-radius: 4px; }
          .status-resolved { color: #198754; font-weight: bold; }
          .status-open { color: #dc3545; font-weight: bold; }
          .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>${reportInfo.title}</h1>
            <h2>Period: ${reportInfo.period}</h2>
          </div>
          
          <div class="section">
            <h3>Report Information</h3>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Report Type:</div>
                <div class="info-value">Breach Summary</div>
              </div>
              <div class="info-item">
                <div class="info-label">Generated By:</div>
                <div class="info-value">${reportInfo.generatedBy}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Site:</div>
                <div class="info-value">${reportInfo.siteName}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Province:</div>
                <div class="info-value">${reportInfo.provinceName}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Breach Summary</h3>
            <div class="summary-grid">
              <div class="summary-item">
                <div class="summary-value">${summary.totalBreaches}</div>
                <div class="summary-label">Total Breaches</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.highSeverity}</div>
                <div class="summary-label">High Severity</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.mediumSeverity}</div>
                <div class="summary-label">Medium Severity</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.lowSeverity}</div>
                <div class="summary-label">Low Severity</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.resolved}</div>
                <div class="summary-label">Resolved</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.open}</div>
                <div class="summary-label">Open</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Breach Details</h3>
            <table class="breach-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Location</th>
                  <th>Province</th>
                  <th>Type</th>
                  <th>Severity</th>
                  <th>Status</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                ${reportData.breachDetails
                  .map(
                    (breach) => `
                  <tr>
                    <td>${new Date(breach.date).toLocaleDateString()}</td>
                    <td>${breach.time}</td>
                    <td>${breach.location}</td>
                    <td>${breach.province}</td>
                    <td>${breach.type}</td>
                    <td><span class="severity-${breach.severity.toLowerCase()}">${breach.severity}</span></td>
                    <td class="status-${breach.status}">${breach.status.charAt(0).toUpperCase() + breach.status.slice(1)}</td>
                    <td>${breach.description}</td>
                  </tr>
                `,
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>Generated on ${reportInfo.generatedAt}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

@Injectable()
export class TransportActivityTemplateService implements TemplateService {
  generateHtml(data: PreparedReportData): string {
    const { reportInfo, data: reportData, summary } = data;

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportInfo.title}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
          .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { text-align: center; border-bottom: 3px solid #2c5aa0; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { color: #2c5aa0; margin: 0; font-size: 28px; }
          .header h2 { color: #666; margin: 10px 0 0 0; font-weight: normal; font-size: 16px; }
          .section { margin-bottom: 30px; }
          .section h3 { color: #2c5aa0; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; font-size: 20px; }
          .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .info-item { padding: 15px; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #2c5aa0; }
          .info-label { font-weight: bold; color: #333; font-size: 14px; }
          .info-value { color: #666; font-size: 16px; margin-top: 5px; }
          .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .summary-item { padding: 20px; background: linear-gradient(135deg, #2c5aa0, #1e3d72); color: white; border-radius: 8px; text-align: center; }
          .summary-value { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
          .summary-label { font-size: 14px; opacity: 0.9; }
          .transport-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; }
          .transport-table th, .transport-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          .transport-table th { background-color: #2c5aa0; color: white; font-weight: bold; }
          .transport-table tr:nth-child(even) { background-color: #f8f9fa; }
          .status-completed { color: #28a745; font-weight: bold; }
          .status-in_progress { color: #fd7e14; font-weight: bold; }
          .status-pending { color: #6c757d; font-weight: bold; }
          .status-acknowledged { color: #28a745; font-weight: bold; }
          .status-new { color: #007bff; font-weight: bold; }
          .status-under_review { color: #ffc107; font-weight: bold; }
          .direction-in { color: #28a745; font-weight: bold; }
          .direction-out { color: #dc3545; font-weight: bold; }
          .overloaded-true { color: #dc3545; font-weight: bold; }
          .overloaded-false { color: #28a745; font-weight: bold; }
          .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>${reportInfo.title}</h1>
            <h2>Period: ${reportInfo.period}</h2>
          </div>
          
          <div class="section">
            <h3>Report Information</h3>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Report Type:</div>
                <div class="info-value">Transport Activity</div>
              </div>
              <div class="info-item">
                <div class="info-label">Generated By:</div>
                <div class="info-value">${reportInfo.generatedBy}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Site:</div>
                <div class="info-value">${reportInfo.siteName}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Province:</div>
                <div class="info-value">${reportInfo.provinceName}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Transport Summary</h3>
            <div class="summary-grid">
              <div class="summary-item">
                <div class="summary-value">${summary.totalActivities}</div>
                <div class="summary-label">Total Activities</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.totalWeight.toFixed(1)}</div>
                <div class="summary-label">Total Weight (tons)</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.completedTrips}</div>
                <div class="summary-label">Completed Trips</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.activeTrips}</div>
                <div class="summary-label">Active Trips</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.uniqueTrucks}</div>
                <div class="summary-label">Unique Trucks</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.averageWeight.toFixed(1)}</div>
                <div class="summary-label">Average Weight (tons)</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.overloadedTrips}</div>
                <div class="summary-label">Overloaded Trips</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.inboundTrips}</div>
                <div class="summary-label">Inbound Trips</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.outboundTrips}</div>
                <div class="summary-label">Outbound Trips</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Transport Activities</h3>
            <table class="transport-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Truck ID</th>
                  <th>Driver</th>
                  <th>Load Weight (tons)</th>
                  <th>Direction</th>
                  <th>Overloaded</th>
                  <th>Site</th>
                  <th>Status</th>
                  <th>Entry Time</th>
                  <th>Exit Time</th>
                </tr>
              </thead>
              <tbody>
                ${reportData.activityDetails
                  .map(
                    (activity) => `
                  <tr>
                    <td>${new Date(activity.date).toLocaleDateString()}</td>
                    <td>${activity.truckId}</td>
                    <td>${activity.driver}</td>
                    <td>${activity.loadWeight.toFixed(1)}</td>
                    <td><span class="direction-${activity.direction}">${activity.direction.toUpperCase()}</span></td>
                    <td><span class="overloaded-${activity.overloaded}">${activity.overloaded ? "YES" : "NO"}</span></td>
                    <td>${activity.site}</td>
                    <td class="status-${activity.status}">${activity.status.charAt(0).toUpperCase() + activity.status.slice(1)}</td>
                    <td>${activity.entryTime ? new Date(activity.entryTime).toLocaleTimeString() : "N/A"}</td>
                    <td>${activity.exitTime ? new Date(activity.exitTime).toLocaleTimeString() : "N/A"}</td>
                  </tr>
                `,
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>Generated on ${reportInfo.generatedAt}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

@Injectable()
export class VolumeTrackingTemplateService implements TemplateService {
  generateHtml(data: PreparedReportData): string {
    const { reportInfo, data: reportData, summary } = data;

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportInfo.title}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
          .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { text-align: center; border-bottom: 3px solid #2c5aa0; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { color: #2c5aa0; margin: 0; font-size: 28px; }
          .header h2 { color: #666; margin: 10px 0 0 0; font-weight: normal; font-size: 16px; }
          .section { margin-bottom: 30px; }
          .section h3 { color: #2c5aa0; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; font-size: 20px; }
          .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .info-item { padding: 15px; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #2c5aa0; }
          .info-label { font-weight: bold; color: #333; font-size: 14px; }
          .info-value { color: #666; font-size: 16px; margin-top: 5px; }
          .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 25px; }
          .summary-item { padding: 20px; background: linear-gradient(135deg, #2c5aa0, #1e3d72); color: white; border-radius: 8px; text-align: center; }
          .summary-value { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
          .summary-label { font-size: 14px; opacity: 0.9; }
          .volume-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; }
          .volume-table th, .volume-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          .volume-table th { background-color: #2c5aa0; color: white; font-weight: bold; }
          .volume-table tr:nth-child(even) { background-color: #f8f9fa; }
          .grade-a { color: #28a745; font-weight: bold; }
          .grade-b { color: #fd7e14; font-weight: bold; }
          .grade-c { color: #dc3545; font-weight: bold; }
          .overloaded-true { color: #dc3545; font-weight: bold; }
          .overloaded-false { color: #28a745; font-weight: bold; }
          .site-summary { margin-top: 20px; }
          .site-summary h4 { color: #2c5aa0; margin-bottom: 10px; }
          .site-summary-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          .site-summary-table th, .site-summary-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          .site-summary-table th { background-color: #2c5aa0; color: white; font-weight: bold; }
          .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>${reportInfo.title}</h1>
            <h2>Period: ${reportInfo.period}</h2>
          </div>
          
          <div class="section">
            <h3>Report Information</h3>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Report Type:</div>
                <div class="info-value">Volume Tracking</div>
              </div>
              <div class="info-item">
                <div class="info-label">Generated By:</div>
                <div class="info-value">${reportInfo.generatedBy}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Site:</div>
                <div class="info-value">${reportInfo.siteName}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Province:</div>
                <div class="info-value">${reportInfo.provinceName}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Volume Summary</h3>
            <div class="summary-grid">
              <div class="summary-item">
                <div class="summary-value">${summary.totalVolume.toFixed(1)}</div>
                <div class="summary-label">Total Volume (tons)</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.totalTrips}</div>
                <div class="summary-label">Total Trips</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.uniqueSites}</div>
                <div class="summary-label">Unique Sites</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.averageVolumePerTrip.toFixed(1)}</div>
                <div class="summary-label">Average Volume/Trip</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.averageFillLevel.toFixed(1)}%</div>
                <div class="summary-label">Average Fill Level</div>
              </div>
              <div class="summary-item">
                <div class="summary-value">${summary.overloadedTrips}</div>
                <div class="summary-label">Overloaded Trips</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h3>Volume Details</h3>
            <table class="volume-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Site</th>
                  <th>Volume (tons)</th>
                  <th>Fill Level (%)</th>
                  <th>Overloaded</th>
                  <th>Truck ID</th>
                  <th>Entry Time</th>
                  <th>Exit Time</th>
                </tr>
              </thead>
              <tbody>
                ${reportData.volumeDetails
                  .map(
                    (volume) => `
                  <tr>
                    <td>${new Date(volume.date).toLocaleDateString()}</td>
                    <td>${volume.site}</td>
                    <td>${volume.volume.toFixed(1)}</td>
                    <td>${volume.fillLevel.toFixed(1)}%</td>
                    <td><span class="overloaded-${volume.overloaded}">${volume.overloaded ? "YES" : "NO"}</span></td>
                    <td>${volume.truckId}</td>
                    <td>${volume.entryTime ? new Date(volume.entryTime).toLocaleTimeString() : "N/A"}</td>
                    <td>${volume.exitTime ? new Date(volume.exitTime).toLocaleTimeString() : "N/A"}</td>
                  </tr>
                `,
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="section">
            <h3>Site Summary</h3>
            <table class="site-summary-table">
              <thead>
                <tr>
                  <th>Site</th>
                  <th>Province</th>
                  <th>Total Volume (tons)</th>
                  <th>Trips</th>
                  <th>Average Volume/Trip</th>
                  <th>Average Fill Level (%)</th>
                  <th>Overloaded Trips</th>
                </tr>
              </thead>
              <tbody>
                ${summary.siteSummary
                  .map(
                    (site) => `
                  <tr>
                    <td>${site.site}</td>
                    <td>${site.province}</td>
                    <td>${site.totalVolume.toFixed(1)}</td>
                    <td>${site.trips}</td>
                    <td>${site.averageVolume.toFixed(1)}</td>
                    <td>${site.averageFillLevel.toFixed(1)}%</td>
                    <td>${site.overloadedTrips}</td>
                  </tr>
                `,
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>Generated on ${reportInfo.generatedAt}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

@Injectable()
export class TemplateServiceFactory {
  constructor(
    private readonly cameraPerformanceTemplate: CameraPerformanceTemplateService,
    private readonly breachSummaryTemplate: BreachSummaryTemplateService,
    private readonly transportActivityTemplate: TransportActivityTemplateService,
    private readonly volumeTrackingTemplate: VolumeTrackingTemplateService,
  ) {}

  getTemplateService(reportType: ReportType): TemplateService {
    switch (reportType) {
      case ReportType.CAMERA_PERFORMANCE:
        return this.cameraPerformanceTemplate;
      case ReportType.BREACH_SUMMARY:
        return this.breachSummaryTemplate;
      case ReportType.TRANSPORT_ACTIVITY:
        return this.transportActivityTemplate;
      case ReportType.VOLUME_TRACKING:
        return this.volumeTrackingTemplate;
      default:
        throw new Error(`Unsupported report type: ${reportType}`);
    }
  }
}
